---
pipeline:
  publish-rke-certs-deployer:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: rancher/hyperkube
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      event: tag
